### ISSUE TITLE
AttributeError: 'module' object has no attribute 'threading'

### ISSUE THREAD

**Issue by ameicler** [Russell91/TensorBox#102]
With this installation:

Mac OSX El Capitan 10.11.6
Tensorflow 0.11
Python 2.7 within Anaconda

I succeeded in compiling TensorBox, but when running command line python train.py --hypes hypes/overfeat_rezoom.json --gpu 0 --logdir output here is the error I receive:

Traceback (most recent call last):
  File "train.py", line 537, in <module>
    main()
  File "train.py", line 534, in main
    train(H, test_images=[])
  File "train.py", line 457, in train
    t = tf.train.threading.Thread(target=thread_loop,
AttributeError: 'module' object has no attribute 'threading'

**Comment by Russell91** [comment]
Interesting, are you using the distributed version of tensorflow?

**Comment by smalhan19** [comment]
I am getting the same issue, I built tensorflow from source

**Comment by Russell91** [comment]
Can you try installing from pip? tf.train.threading is in the API for me with 0.11rc1 and 0.11rc2.

**Comment by ameicler** [comment]
Spot on. Succeeded in training the model  when installing via pip :-)

Thanks a lot.
