### ISSUE TITLE
TensorFlow 0.11.0rc2 AttributeError: 'module' object has no attribute 'threading'

### ISSUE THREAD

**Issue by panovr** [Russell91/TensorBox#107]
Using TensorFlow 0.11.0 rc2, invoke 'python train.py --hypes hypes/overfeat_rezoom.json --gpu 0 --logdir output' gets this error:

```
Traceback (most recent call last):
  File "train.py", line 537, in <module>
    main()
  File "train.py", line 534, in main
    train(H, test_images=[])
  File "train.py", line 457, in train
    t = tf.train.threading.Thread(target=thread_loop,
AttributeError: 'module' object has no attribute 'threading'

```

**Comment by Russell91** [comment]
Did you install via pip? Someone else had this issue as well.

**Comment by panovr** [comment]
No, I installed TensorFlow from source.

**Comment by neuralearner** [comment]
Same issue here as well. I installed from source.

**Comment by Russell91** [comment]
Actually @panovr @neuralearner can one of you confirm where the threading module is in your tensorflow. E.g. does from tensorflow.train import threading work even though tf.train.threading is missing?

**Comment by ajtao** [comment]
FWIW, I was running into this issue and changed:
            t = tf.train.threading.Thread(target=thread_loop ...
to:
            t = threading.Thread(target=thread_loop ...
... and also added import threading at top of train.py

**Comment by Russell91** [comment]
Okay, just pushed this change.
