### ISSUE TITLE
issue with evaluate.ipynb

### ISSUE THREAD

**Issue by mdlai** [Russell91/TensorBox#11]
Hi,

I'm having an issue with importing stitch_wrapper in the evaluate.ipynb.

The line:
from utils.stitch_wrapper import stitch_rects

Causes the error:
ImportError: utils/stitch_wrapper.so: undefined symbol: PyFPE_jbuf

I'm on tensorflow 7.1.0 in anaconda.  Python version 2.7.11

**Comment by Russell91** [comment]
Looks like there is some sort of compilation issue happening for you. Stitch_wrapper.so is created by compiling stitch_wrapper.pyx in utils/Makefile. Maybe you can try removing the .so and recompiling with `	makecython++ stitch_wrapper.pyx "" "stitch_rects.cpp ./hungarian/hungarian.cpp"`

**Comment by PureDiors** [comment]
Same issue here. The problem is solved by the cmd:  makecython++ stitch_wrapper.pyx "" "stitch_rects.cpp ./hungarian/hungarian.cpp".  Thanks.@Russell91

**Comment by mdlai** [comment]
Still no luck.  Must be something weird on my end.

I'll just bypass it with use_stitching=False  Thanks for the help!

**Comment by scream7** [comment]
makecython++ stitch_wrapper.pyx "" "stitch_rects.cpp ./hungarian/hungarian.cpp
dosen't work

**Comment by mdlai** [comment]
import stitch_wrapper works when I use my system python instead of anaconda.  I'm still not sure how to fix it for anaconda, but this works at least.

**Comment by Russell91** [comment]
@mdlai can you try running

    pip install --upgrade runcython

and see if this fixes all of the issues you were having without the PKG_CONFIG_PATH update you applied?

**Comment by mdlai** [comment]
Yep that looks like it works without the PKG_CONFIG_PATH now!
