### ISSUE TITLE
dlopen error on importing opencv2

### ISSUE THREAD

**Issue by rakeen** [Russell91/TensorBox#113]
ImportError: dlopen: cannot load any more object with static TLS
![screenshot from 2016-11-11 15-48-08](https://cloud.githubusercontent.com/assets/10359412/20210956/4e4238f8-a826-11e6-8ea9-c820bb029322.png)

**Comment by ilaripih** [comment]
I solved this by importing cv2 before tensorflow.

**Comment by rakeen** [comment]
cv2 is already being imported before tensorflow in `train_utils.py`

**Comment by ilaripih** [comment]
Yes, but `train.py` imports tensorflow before cv2, that's the problem.

**Comment by rakeen** [comment]
I had commented that out previously. But putting cv2 before tf also give the same error.

**Comment by rakeen** [comment]
importing cv2 at the very beginning solved the problem.  

I was using docker, that might have restricted the "TLS memory".
more on that [here](http://www.advanpix.com/2016/02/22/matlab-error-cannot-load-any-more-object-with-static-tls/)  

<br>
[Thread Local Storage | TLS](https://en.wikipedia.org/wiki/Thread-local_storage)

**Comment by v3yr0n** [comment]
like @rakeen i've included cv2 at the beginning of train.py file and it works now. Maybe it should be added to the repo?

**Comment by Russell91** [comment]
Can you submit a pull request?
