### ISSUE TITLE
Seg Fault while training lstm_rezoom

### ISSUE THREAD

**Issue by arushk1** [Russell91/TensorBox#116]
Hi, I'm trying to train the Reinspect algorithm by using the lstm_rezoom hypes file, but I'm constantly running into a seg fault.

`
python train.py --hypes hypes/lstm_rezoom.json --gpu 1 --logdir output
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.BasicLSTMCell object at 0x7fa9ea9fed50>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
Segmentation fault (core dumped)

`

Note that I'm able to train overfeat_rezoom by using exactly the same parameters. 

Any help?

**Comment by Russell91** [comment]
Is anyone else getting this issue?

**Comment by juergen3** [comment]
I have run into the same warning regarding the BasicLSTMCell but without the seg fault (not using CUDA) on Ubuntu 16.04, g++ 5.4.0-6, Tensorflow 0.11.0rc2. What stopped it running in my case though was...

tensorflow.python.framework.errors.NotFoundError: utils/hungarian/hungarian.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev

Some more info on this error is here: https://github.com/tensorflow/tensorflow/issues/1569

I then modified the utils/Makefile to build the hungarian library passing 

-D_GLIBCXX_USE_CXX11_ABI=0

as an additional parameter to g++, so the line in the Makefile reads:

g++ -std=c++11 -shared hungarian.cc -o hungarian.so -fPIC -I $$TF_INC -D_GLIBCXX_USE_CXX11_ABI=0

This solved the issue for me. I'm not sure if that helps in your case but maybe its worth a try.

**Comment by Russell91** [comment]
this should be fixed here:

https://github.com/Russell91/TensorBox/commit/e8d90bde653817c96e16368e3eff42e7758e91ed

**Comment by zhihongzeng** [comment]
I have the same issue (work env: ubuntu 16.04 LTS, tensorflow version 0.11.head). Here is the output:

python train.py --hypes hypes/overfeat_rezoom.json --gpu 0 --logdir output
WARNING:tensorflow:From train.py:463 in train.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
WARNING:tensorflow:From train.py:472 in train.: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2016-03-02.
Instructions for updating:
Please use tf.global_variables instead.
Segmentation fault (core dumped)
zhihong@zhihong-latitude:~/dev/tensorbox$ python train.py --hypes hypes/overfeat_rezoom.json --gpu 0 --logdir output
WARNING:tensorflow:From train.py:463 in train.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
WARNING:tensorflow:From train.py:472 in train.: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2016-03-02.
Instructions for updating:
Please use tf.global_variables instead.
Segmentation fault (core dumped)
