### ISSUE TITLE
issues using different dataset

### ISSUE THREAD

**Issue by Prince-kapoor1991** [Russell91/TensorBox#119]
I used your overfeat-inception model on caltech data set and performance comes out to be little bit low. I am attaching my performance curve of Log(FPPI-Missrate).
![results-orig](https://cloud.githubusercontent.com/assets/23203205/20325638/8af07f28-ab53-11e6-8993-2c1a5ede7129.png)
Please, suggest me if anything more I can do with this. 
Also, I want to try it on reinspect algorithm but running it some errors when "make hungarian"

cd hungarian && \
	TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())') && \
	@if [ `uname` == Darwin ]; then g++ -std=c++11 -shared hungarian.cc -o hungarian.so -fPIC -I $TF_INC; else g++ -std=c++11 -shared hungarian.cc -o hungarian.so -fPIC -I -D_GLIBCXX_USE_CXX11_ABI=0 $TF_INC; fi
/bin/bash: -c: line 2: syntax error near unexpected token `then'
/bin/bash: -c: line 2: `@if [ `uname` == Darwin ]; then g++ -std=c++11 -shared hungarian.cc -o hungarian.so -fPIC -I $TF_INC; else g++ -std=c++11 -shared hungarian.cc -o hungarian.so -fPIC -I -D_GLIBCXX_USE_CXX11_ABI=0 $TF_INC; fi'
make: *** [hungarian/hungarian.so] Error 1

**Comment by Russell91** [comment]
Wrt problem 2, please reclone the repository and check again. Wrt caltech, we haven't actually run on caltech before. You might want to do something to look at the small number of positive examples there. Also, try to get a sense of whether the regression or classification performance is the problem. If you have comparisons to e.g. Faster RCNN, those would be interesting too. Our model should perform almost exactly the same as Faster RCNN if optimized for the dataset.

**Comment by Prince-kapoor1991** [comment]
Ok, thanks for the help. I'll try that too...

**Comment by Prince-kapoor1991** [comment]
Wrt to the problem mentioned for "make hungarian", it is not resolved.
I reclone the repository but the same error is coming as mentioned below

cd hungarian && \
	TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())') && \
	@if [ `uname` == Darwin ]; then g++ -std=c++11 -shared hungarian.cc -o hungarian.so -fPIC -I $TF_INC; else g++ -std=c++11 -shared hungarian.cc -o hungarian.so -fPIC -I -D_GLIBCXX_USE_CXX11_ABI=0 $TF_INC; fi
/bin/bash: -c: line 2: syntax error near unexpected token `then'
/bin/bash: -c: line 2: `@if [ `uname` == Darwin ]; then g++ -std=c++11 -shared hungarian.cc -o hungarian.so -fPIC -I $TF_INC; else g++ -std=c++11 -shared hungarian.cc -o hungarian.so -fPIC -I -D_GLIBCXX_USE_CXX11_ABI=0 $TF_INC; fi'
make: *** [hungarian/hungarian.so] Error 1

**Comment by Russell91** [comment]
Updated again - mixed up OSX and Linux ordering in the fix.

**Comment by Prince-kapoor1991** [comment]
Now, that works, thanks....
