### ISSUE TITLE
Question about the stitching algorithm

### ISSUE THREAD

**Issue by lanchao** [Russell91/TensorBox#130]
Hi, I've read the stitching algorithm implementation and can not understant the 'thresholds' list defined in 'util/stitch_wrapper.pyx'. The values in the thresholds are:
    thresholds = [(.80, 1.0),
                  (.70, 0.9),
                  (.60, 0.8),
                  (.50, 0.7),
                  (.40, 0.6),
                  (.30, 0.5),
                  (.20, 0.4),
                  (.10, 0.3),
                  (.05, 0.2),
                  (.02, 0.1),
                  (.005, 0.4),
                  (.001, 0.01),
                  ]

The threshold pair of (.005, 0.4) seems to be a little strange to me. According to my understanding of the code, those pairs of thresholds work like filters in the stitching process. Based on the rest of pairs, something like (.005, 0.04) seems to be more logical. Why use (.005, 0.4)? Thanks.

**Comment by Russell91** [comment]
Ah, good catch. 0.04 looks like a better value. Shouldn't matter a huge
amount, but would be a good idea to change. Please submit a pull request if
you can.
