### ISSUE TITLE
kitti frame rate can reach 0.15s on cpu 2.5hz (1 core)?

### ISSUE THREAD

**Issue by sophiehust** [Russell91/TensorBox#132]
Hello @Russell91
I see that on kitti webside the reinspect can reach 0.15s on  1 core cpu (2.5hz),
since you provide two versions of reinspect, one is tensorbox (tensorflow), the other is on caffe,
I'm not sure which one can reach the frame rate on cpu (0.15s, or about 6-7fps), 
so could you please advise the frame rate about reinspect version on cpu?  thanks.

**Comment by Russell91** [comment]
That number was the GPU on a Titan 780ti at the time of submission. It is
incorrect for CPU - we'll get it fixed. Thanks for the notification!
