### ISSUE TITLE
Some queries in paper.

### ISSUE THREAD

**Issue by parhartanvir** [Russell91/TensorBox#134]
Hi Russell,
I have the following queries in regarding your paper

1) Correct me if I am wrong. The network has 300 distinct LSTM controllers
for 300 distinct 1024 dimensional vectors and each module outputs boxes in
an overlap of central 64x64 px. region of the receptive field of 139x139
px. In that case, why does an LSTM module with a single 1024 dimensional
vector show detection at varying parts of the image?

2) You said that 300 distinct LSTM controllers run in parallel for each of
the 1x1x1024 vectors. And at each step you concatenate the GoogLeNet
features with the output of the previous LSTM unit, and feed the result
into the next LSTM unit. By LSTM unit do you mean a decoder LSTM unit or a
memory state unit? If it is the former case, won't the processing be
serial and not parallel?

I hope these are legit doubts.

Thanks for the wonderful paper. Keep up the good work!

Tanvir

**Comment by Russell91** [comment]
1) The single 1024 dimensional vector is a distributed encoding of information. In this case, to be successful, it must encode the locations of all objects in a 64x64 region relative to the center of that region.

2) The "LSTM Unit" refers to one iteration of the LSTM. The initial hidden state for the LSTM has dimensions 300x1024, and thus we run all 300 separate image regions in batch.

Hope this clears things up a little. Good questinos!

**Comment by parhartanvir** [comment]
Yes. I think i got you.
By region you mean 139x139 receptive field?
Thanks!

**Comment by Russell91** [comment]
Yes and no. The receptive field of these neurons is 139x139, but they only predict objects intersecting the central 64x64 region of that receptive field. This way they only predict objects for which they have sufficient context.
