### ISSUE TITLE
Error in importing rect.py

### ISSUE THREAD

**Issue by parhartanvir** [Russell91/TensorBox#136]
I have the following error when I run train.py 

` File "utils/stitch_wrapper.pyx", line 4, in init utils.stitch_wrapper (stitch_wrapper.cpp:4517)
    from utils.rect import Rect as PyRect`
`SystemError: Parent module '' not loaded, cannot perform relative import`

For now I have copied the Rect class definition in stitch_wrapper.pyx.

But can you give some insights into the error? 
I am using Python3.4. and ran make with makecython3++ in MakeFile.

**Comment by Russell91** [comment]
Sorry, but we will not be supporting python3.

**Comment by parhartanvir** [comment]
@Russell91 , that's not a problem. I am able to work without the import, by defining the class in the   stitch_wrapper.pyx file. By any chance, would you be knowing the root of [this](https://github.com/Russell91/TensorBox/issues/137) error?
