### ISSUE TITLE
Package python was not found in the pkg-config search path

### ISSUE THREAD

**Issue by Chandrak1907** [Russell91/TensorBox#138]
hi Russell,

I was able to execute TensorBox on my mac.  I wanted to run this code on AWS GPU to speed up. 
I am facing issue with make command:

`makecython++ stitch_wrapper.pyx "" "stitch_rects.cpp ./hungarian/hungarian.cpp`
 

I get below error:

> Package python was not found in the pkg-config search path.
Perhaps you should add the directory containing `python.pc'
to the PKG_CONFIG_PATH environment variable
No package 'python' found
stitch_wrapper.cpp:4:20: fatal error: Python.h: No such file or directory
 #include "Python.h"
                    ^
compilation terminated.

From here [http://stackoverflow.com/questions/11303730/pkg-config-cannot-find-pc-files-although-they-are-in-the-path](url),  I got list of  directories pkg-config looks using below command:

`pkg-config --variable pc_path pkg-config`

> /usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig

I used export PKG_CONFIG_PATH to above directories. Still the error persists.

Can you pls help me, how to resolve this?
Thank you,

**Comment by Chandrak1907** [comment]
I could resolve it by installing python 2.7 instead of 3.4

**Comment by nerdykamil** [comment]
![image](https://user-images.githubusercontent.com/19584358/37283886-d86dc81c-25b6-11e8-9971-d9319ed4a971.png)

Hey I still got the same error even after installing python 2.7 instead of 3.4, any leads?

**Comment by F1iX** [comment]
For me on Arch Linux (4.15.11-1), makecython was unable to find `python.pc` too.
I checked `pkg-config --variable pc_path pkg-config` and found out that the respective searchpath only contained the files `python3.pc` and `python2.pc`. So I added a symlink using `sudo ln -s /usr/lib/pkgconfig/python3.pc /usr/lib/pkgconfig/python.pc` and now everything works fine.

**Comment by tmsd2001** [comment]
The error can have several causes. First you must start Tensorbox in your Virtual environment, if you use one. And as F1iX already said you need a symlink. And I can only speak for me, all Tensorflow make problems with python 3. I run all at Python 2.7 with VirtualEnv.

**Comment by captaintong** [comment]
For me I installed python3.5 by Anaconda. So I have resolved it by running this command :
`sudo ls PATH_TO_INSTALLED_ANACONDA3/lib/pkgconfig/python-3.5.pc /usr/lib/pkgconfig/python.pc`

``PATH_TO_INSTALLED_ANACONDA3``is the installed location of your Anaconda3.

If you installed python in other ways, you can find the ``python-*.pc`` file in `PATH_TO_INSTALLED_PYTHON/lib/pkgconfig`.
