### ISSUE TITLE
How did you label your test data?

### ISSUE THREAD

**Issue by jbrozena22** [Russell91/TensorBox#139]
Thank you so much for your work on this, it's incredibly helpful.

Question though. You have collected and tagged a bunch of test data in JSON format, showing the location of a box on a camera frame.

How did you go about creating that test data in the first place? Did you use a service that makes it easy to drag and drop boxes on photos and converts it to position data? Did you do it all by hand?

Thanks!

**Comment by Russell91** [comment]
We labeled the dataset using mechanical turk. We developed custom tools for setting up a website that users could log into and tag boxes on various image. At scale, it costs about 1-2 cents per box to do this.

**Comment by jbrozena22** [comment]
Great, thanks for the answer!

**Comment by guiyuliu** [comment]
hello russell,
your work is very helpful to me too,
I want to ask whether the labeling tools and websites are opensource or not ,because I  want to use my own data to do some experiments,
thanks!
