### ISSUE TITLE
Error google-net.pb not found

### ISSUE THREAD

**Issue by arjungrylls** [Russell91/TensorBox#156]
I followed the steps on HP i3 notebook without any GPU. I downloaded and saved the checkpoint files and datasets separetely without following ./download_data.sh .I got the same error as above googlenet.pb not found !!!

File "/home/arjun/TensorBox-master/TensorBox-master/utils/googlenet_load.py", line 24, in init
with open(graph_def_orig_file) as f:
IOError: [Errno 2] No such file or directory: '/home/arjun/TensorBox-master/TensorBox-master/utils/../data/googlenet.pb'

Anyone pls help me. Can't really understand the #80 solution..

**Comment by arjungrylls** [comment]
Use this :  http://russellsstewart.com/s/tensorbox/googlenet.pb

**Comment by PumayHui** [comment]
I didn't find the file 'google-net.pb', can you give me some me advices? Thank you very much! @arjungrylls
