### ISSUE TITLE
Description header Image

### ISSUE THREAD

**Issue by zeshanb** [Russell91/TensorBox#159]
Seems to be an issue with image in description of your project. Very strange to ask such a question of another human being. Here goes:
Does detection of human beings head equate object?

**Comment by arjungrylls** [comment]
@zeshanb , this tensorbox is a model or prototype where you can train to detect object. I have succesfully used this to detect crops in a image. Russell used a standard brainwash dataset (human beings head )  to illustrate his work . U can explore issues to see few people have able to identify airplanes, scripts etc

**Comment by zeshanb** [comment]
Does detection of human beings head equate to detection of an object i.e. apple, banana, books, candy bar?

**Comment by zeshanb** [comment]
Personally, in regard to this project. I am on the consumer side of this just as those beings in the coffee shop. Please print out the description of your project and take to university where you studied or a local university and get their advice?

**Comment by zeshanb** [comment]
Begin by sending a copy to these individuals:
[Faculty of Anthropology and history] ](http://lsa.umich.edu/anthro/people/graduate-students/anthropology---history.directory.html)

**Comment by arjungrylls** [comment]
Yes it does equate

**Comment by arjungrylls** [comment]
I can't understand you brother, why I have to go and get advice ?

**Comment by zeshanb** [comment]
This is not a proper place to discuss this and I not the right person to have this conversation with you. Please send copy of the description to each of these individuals:

http://lsa.umich.edu/anthro/people/graduate-students/anthropology---history.directory.html

**Comment by atique81** [comment]
I think, you can use Russel's approach for detection of objects that the feature detector network (which is GoogleNet, in this case) was trained on.
