### ISSUE TITLE
Larger batch size?

### ISSUE THREAD

**Issue by bernardopires** [Russell91/TensorBox#16]
Hi,

first thanks for implementing overfeat and huval's paper in Tensorflow! This is of great help for me. I've been training using your code and was wondering why the GPU seems not to be heavily used. It stays in this cycle: peaks briefly at 99% and then seems to spend most of the time back at 0-5%. I'm wondering if it's because of the small batch size? Is it a requirement to use `batch_size` 1?

Thanks,
Bernardo

**Comment by Russell91** [comment]
Using larger batch size will indeed work! However, note that detection frequently uses smaller batch sizes than classification (e.g. Faster-RCNN uses 1 image per training iteration as well). I get slight speedups for larger batch sizes (maybe 20%), but not enough to turn TensorSlow into TensorFast :(.
