### ISSUE TITLE
Clarification about the architecture

### ISSUE THREAD

**Issue by bernardopires** [Russell91/TensorBox#17]
Hi,

This is more a clarification about the architecture since it's a little hard to read what's going on because of the reverse engineering to load Inception. If I don't use LSTMs, is the architecture simply Inception up to `mixed5b` followed by two parallel FC layers? One FC layer uses softmax to get confidences and the other one is simply a bounding box regression? 

I was a little confused because there is code regarding `avgpool0` (which theoretically would come after `mixed5b`) and early loss layers, but it seems like they're actually never used. Or am I understanding something wrong?

Thanks

**Comment by Russell91** [comment]
Yes, the overfeat model uses GoogLeNet followed by 2 independent FC layers for softmax and regression. Note that there is a dropout layer on the GoogLeNet features as well.
