### ISSUE TITLE
Error while running TensorBox

### ISSUE THREAD

**Issue by jadielam** [Russell91/TensorBox#20]
When running tensor box it throws the following error: 

IOError: [Errno 2] No such file or directory: '/Users/dearj019/Documents/workspace/tensorbox/utils/../data/googlenet.pb'

That file referenced there is not in the repository.

**Comment by arjungrylls** [comment]
I followed the steps on HP i3 notebook without any GPU. I downloaded and saved the checkpoint files and datasets separetely without following ./download_data.sh .I got the same error as above  googlenet.pb not found !!! 

 File "/home/arjun/TensorBox-master/TensorBox-master/utils/googlenet_load.py", line 24, in init
    with open(graph_def_orig_file) as f:
IOError: [Errno 2] No such file or directory: '/home/arjun/TensorBox-master/TensorBox-master/utils/../data/googlenet.pb'

Anyone pls help me. Can't really understand the #80 solution..
