### ISSUE TITLE
TensorBox with Tensorflow in Window plateform

### ISSUE THREAD

**Issue by derrickpang** [Russell91/TensorBox#206]
Upon the installation of tensorflow in window, the following command is executed

 _python train.py --hypes hypes/overfeat_rezoom.json --gpu 0 --logdir output_

However, some errors are occurred. Anyone done the installation in window plateform and successfully run the above command?

Thanks

**Comment by PumayHui** [comment]
You should give us some instructions about errors...

**Comment by RomanSteinberg** [comment]
Due to lack of activity the issue would be closed
