### ISSUE TITLE
How to detect multiple object classes with one network?

### ISSUE THREAD

**Issue by johnhobbs254** [Russell91/TensorBox#250]
I've gotten the basic example working - detecting one class of objects (such as faces), but let's say I want to detect faces and t-shirts. Any examples on how to train with multiple classes?

**Comment by Jflima92** [comment]
I would like to know this aswell. I don't know if it's possible with tensorbox.. If not, I'll give a shot on my own implementation.

**Comment by twhitloc** [comment]
Multiclass is currently not a supported inference mode right now.  @RomanSteinberg maintains a fork that is currently working on this as far as I am aware.  Any reference to num_classes in the actual code base are currently just pieces of a partial implementation.

**Comment by RomanSteinberg** [comment]
This issue duplicates #210
