### ISSUE TITLE
Import error: No module named cv2

### ISSUE THREAD

**Issue by urvashibhavsar** [Russell91/TensorBox#251]
I get this error when i try to run 
"python train.py --hypes hypes/overfeat_rezoom.json --gpu 0 --logdir output"
I have opencv 2.4 installed. any help would be appreciated!

**Comment by privard** [comment]
pip install opencv-python fixed it for me

**Comment by Sakshiabc** [comment]
I have installed Opencv 3 in raspberrypi 3 model B
when i am running my python 3 program 
Importerror: No module named "cv2"

**Comment by mavyasoni786** [comment]
I have used this command but I am still getting. 

Command : 

> pip3 install opencv-python 

Error : 

> Traceback (most recent call last):
>   File "labelling-character.py", line 3, in <module>
>     import cv2
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cv2/__init__.py", line 4, in <module>
>     from .cv2 import *

**Comment by tmsd2001** [comment]
Hallo, best use python 2.7 for Tensorbox.
