### ISSUE TITLE
build_lstm_inner not defined

### ISSUE THREAD

**Issue by shivenmian** [Russell91/TensorBox#252]
Set use_lstm: true in the overfeat hypes file, but in train.py, there isn't a function `build_lstm_inner`.

**Comment by Elliyos** [comment]
Managed to fix this particular error by grabbing code from an earlier merge. This is the method:

`def build_lstm_inner(H, lstm_input):
    '''
    build lstm decoder
    '''
    lstm_cell = rnn_cell.BasicLSTMCell(H['lstm_size'], forget_bias=0.0, state_is_tuple=True, reuse=tf.get_variable_scope().reuse)
    if H['num_lstm_layers'] > 1:
        lstm = rnn_cell.MultiRNNCell([lstm_cell] * H['num_lstm_layers'], state_is_tuple=True)
    else:
        lstm = lstm_cell

    batch_size = H['batch_size'] * H['grid_height'] * H['grid_width']
    state = lstm.zero_state(batch_size, tf.float32)

    outputs = []
    with tf.variable_scope('RNN', initializer=tf.random_uniform_initializer(-0.1, 0.1)):
        for time_step in range(H['rnn_len']):
            if time_step > 0: tf.get_variable_scope().reuse_variables()
            output, state = lstm(lstm_input, state)
            outputs.append(output)
    return outputs`

Started getting an RNNCell reuse error after this that I haven't managed to crack yet. Read something about creating a "reuse" parameter and setting "state_is_tuple" to false but neither worked on my end. Best of luck!

**Comment by fujingling** [comment]
Hi,@shivenmian,I got the same problem with you, have you resolved it?
