### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by zoid-anurag** [Russell91/TensorBox#254]
train step results in error. See the screenshot. Newbie here please help. 
![screenshot from 2017-07-05 03-06-06](https://user-images.githubusercontent.com/22439738/27859924-46c6d13e-612f-11e7-95bc-f976f1cf2612.png)

**Comment by mrlzla** [comment]
cd utils && make && make hungarian

**Comment by Zumbalamambo** [comment]
How do I run this on windows?

**Comment by mrlzla** [comment]
I recommend you to look through this [fork](https://github.com/cheind/TensorBox/tree/develop).

**Comment by Zumbalamambo** [comment]
okay but make is not working in windows

**Comment by mrlzla** [comment]
Go to link

**Comment by Zumbalamambo** [comment]
yes... I have downloaded [this](https://github.com/cheind/TensorBox/tree/develop)

then I ran make in `utils `folder.

It fired the following error

>  Python.h: No such file or directory
> compilation terminated.

**Comment by Elliyos** [comment]
I was getting a similar error. Fixed it by installing libgcc

**Comment by Zumbalamambo** [comment]
i tried [this](https://github.com/lilohuang/TensorBox-Windows) but it is not working too

**Comment by Zumbalamambo** [comment]
How do I evaluate it in a realtime video?
