### ISSUE TITLE
Error in train:  TypeError: variable_scope() got multiple values for keyword argument 'reuse'

### ISSUE THREAD

**Issue by fujingling** [Russell91/TensorBox#259]
I have a problem in train step, the following is my log and error information, anyone knows how can I solve this problem. thank you very much!

[ar@JQ-0-0-4 tensorbox]$ python train.py --hypes hypes/overfeat_rezoom.json --gpu 0 --logdir output
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "train.py", line 524, in <module>
    main()
  File "train.py", line 521, in main
    train(H, test_images=[])
  File "train.py", line 423, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train.py", line 316, in build
    boxes_loss[phase]) = build_forward_backward(H, x, phase, boxes, flags)
  File "train.py", line 217, in build_forward_backward
    pred_confidences, pred_confs_deltas, pred_boxes_deltas) = build_forward(H, x, phase, reuse)
  File "train.py", line 104, in build_forward
    cnn, early_feat = googlenet_load.model(x, H, reuse)
  File "/export/home/aiusr/liuming/tianchi/fjl/tensorbox/utils/googlenet_load.py", line 18, in model
    reuse=reuse)
  File "/export/home/aiusr/liuming/tianchi/fjl/tensorbox/utils/slim_nets/inception_v1.py", line 287, in inception_v1
    reuse=reuse) as scope:
  File "/export/home/aiusr/env/img/lib/python2.7/contextlib.py", line 84, in helper
    return GeneratorContextManager(func(*args, **kwds))
TypeError: variable_scope() got multiple values for keyword argument 'reuse'

**Comment by RomanSteinberg** [comment]
@fujingling have you found the solution? As far as I remeber I gave you advice in gitter chat.

**Comment by fujingling** [comment]
@RomanSteinberg Thank you for your help, I have solved my problem, it was my environmental variables‘s error caused this problem.

**Comment by mrlzla** [comment]
reuse=None

**Comment by RomanSteinberg** [comment]
ok, then
