### ISSUE TITLE
train_data_fixed_3.json missing

### ISSUE THREAD

**Issue by willSapgreen** [Russell91/TensorBox#286]
In lstm_mobilenet_rezoom.json,
train_idl is specified to train_data_fixed_3.json.
However,
I cannot find train_data_fixed_3.json.
Can anyone help me on this issue?
Thank you.

**Comment by EverettBerry** [comment]
This file should be the name of the json file which specifies the training data. So I believe the default file is `train.json` or you can make your own with `python make_json.py train_data_fixed_3.json`.

**Comment by willSapgreen** [comment]
Instead of making my own train_data_fixed_3.json,
I replace it with "train_idl": "./data/brainwash/train_boxes.json", same as in overfeat_rezoom.json.
But I encounter another issue related to MobilenetV1, which is not related to this issue title.
So I think you can close this issue.
Thank you very much for helping.
