### ISSUE TITLE
ImportError: /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow9ConcatCPUINS_8bfloat16EEEvPNS_10DeviceBaseERKSt6vectorISt10unique_ptrINS_6TTypesIT_Li2EiE11ConstMatrixESt14default_deleteIS9_EESaISC_EEPNS8_6MatrixE

### ISSUE THREAD

**Issue by Lexicographical** [Russell91/TensorBox#289]
I built Tensorflow from source on Raspbian Stretch but when I try to launch it, it says it failed to launch. I posted the full stack trace here:

https://stackoverflow.com/questions/49203553/tensorflow-on-raspbian-stretch-importerror

**Comment by RomanSteinberg** [comment]
This is not TensorBox issue. Please, report it in the [Tensorflow repo](https://github.com/tensorflow/tensorflow).
