### ISSUE TITLE
Training on Personal Dataset

### ISSUE THREAD

**Issue by DrewNF** [Russell91/TensorBox#29]
Hi Russell91! 
I train the net to recognize airplane and after one million iteration training, the result is the following:
![frame8](https://cloud.githubusercontent.com/assets/2854222/16001053/5d5bd97c-3150-11e6-8b08-2ded4bcf1cc1.jpg)
![frame9](https://cloud.githubusercontent.com/assets/2854222/16001054/5d5d482a-3150-11e6-8968-fb2e60c22e40.jpg)

Do you have any suggestion on why doesn't start recognize the airplane? bests regards Drew

**Comment by DrewNF** [comment]
Can you tell me in which order are readed and write the bb coordinates? xmax, xmin, ymax, ymin or which?

**Comment by DrewNF** [comment]
Hi Russell91!!
I go in deep in code to see why i was retrievering that bad image or nothing (the bb values in the idl file were almost right), so I implement by my self the bb drawing on the image and this is the final result.


![frame1 16 50 51](https://cloud.githubusercontent.com/assets/2854222/16046404/a1f938a2-324c-11e6-8283-d37f3abd3ddb.jpg)
![frame2 16 50 51](https://cloud.githubusercontent.com/assets/2854222/16046405/a2142220-324c-11e6-9b17-07b71f806309.jpg)


For evaluate I use the code into the py notebook (copy/paste to be clear), this could be an hint for someone else having the same problem or for you to check a possible inversion of coordinates in the addRectangle function. Best Regards

**Comment by DrewNF** [comment]
Hi Russell!
Can you tell me if the order of the readed coordinates is the following : 
<img width="661" alt="screenshot 2016-06-21 10 28 20" src="https://cloud.githubusercontent.com/assets/2854222/16223022/9893c63e-379b-11e6-8c3f-8f87a11dba72.png">


Because I want to get the best train ever and this could be an entry point for errors. In DET dataset the order is xmin xmax ymin ymax, in VID are xmax xmin ymax ymin, so your x1 y1 x2 y2 at which correspond? sorry coulb be a stupid question but for me its important :) bests

**Comment by AldoMarzullo** [comment]
Dear all,
I train the net to recognize optic nerve but up to now I can not see any output:
![issue](https://cloud.githubusercontent.com/assets/8161416/17642675/d7ca50d4-614e-11e6-96f3-9c85350783cf.jpg)

Moreover the weird thing is that I am getting an Accuracy of 99%:
`Step: 1200, lr: 0.001000, Train Loss: 0.08, Test Accuracy: 99.0%, Time/image (ms): 471.9`

Am I doing something wrong?

**useful links**
The [hype.json](http://pastebin.com/drxR47Ci) file
The [train.json](http://pastebin.com/1z7HbD9U) file
