### ISSUE TITLE
TensorBox on Python 3.x, an issue with stitchwrapper.so

### ISSUE THREAD

**Issue by acerekovic** [Russell91/TensorBox#34]
I am trying to run TensorBox on Python 3.5 with Anaconda, with Tensorflow 0.8 on Ubuntu 14.04. 
However,[ train.py](https://github.com/Russell91/TensorBox/blob/master/train.py) produces an error trying to read utils/stitchwrapper.so, as reported:  
```ImportError: ../code/tensorbox/utils/stitch_wrapper.so: undefined symbol: PyFPE_jbuf ```   

I created stitchwrapper.so using modified[ Makefile](https://github.com/Russell91/TensorBox/blob/master/utils/Makefile) for Python 3, as follows: 

```
SHELL := /bin/bash

.PHONY: all
all:
	cd /opt/anaconda3/bin/
	pip install runcython3
	makecython3++ stitch_wrapper.pyx "" "stitch_rects.cpp ./hungarian/hungarian.cpp"
```

Further, I tried to edit [stitch_wrapper.pyx](https://github.com/Russell91/TensorBox/blob/master/utils/stitch_wrapper.pyx) and recompile the stitchwrapper.so to see what causes the error. Weirdly enough, when I remove the following part:   
```
    for i, row in enumerate(all_rects):
        c_rects.push_back(c_row)
        for j, column in enumerate(row):
            c_rects[i].push_back(c_column)
            for py_rect in column:
                c_rects[i][j].push_back(
                    Rect(
                        py_rect.cx,
                        py_rect.cy,
                        py_rect.width,
                        py_rect.height,
                        py_rect.confidence)
                    )
```
the training starts. When I insert the following back again:
```

    for i, row in enumerate(all_rects):
        print('dummy')
```
train.py produces the same import error.

Although the code is created for Python 2.x, do you happen to know what can be a quick fix for this issue?  

Thanks

**Comment by Russell91** [comment]
Hey, sorry about this. There was a feature added in runcython2 [here](https://github.com/Russell91/runcython/commit/c818a91c8624dae40ed27fbff10ad1eb415fa42a) allowing  for implicit usage of anaconda. That feature was not pushed in runcython3. I just made an update supporting this in runcython3 version 0.2.7. If you run `pip install --upgrade runcython3`, everything should work. Also, if the changes necessary for python3 are minimal, please consider pushing some sort of pull request with your modifications. Worst case, I will just leave it up for others to look at an comment on. Best case, I'll merge in some sort of py2/3 compatibility Good luck!

**Comment by acerekovic** [comment]
Cool, thanks a lot, it works now! 

The changes to Python 3 are minimal,  stuff like xrange -> range, iteritem() -> list(items()), some encoding + changes coming from the Tensorflow v0.8 API. Besides, Makefile from utils had to be modified as mentioned above (if one is using Anaconda). I will re-check things and push the code so you can do whatever it can be done.

Btw, runcython is quite straightforward to use.

**Comment by debapriyamaji** [comment]
@Russell91  any suggestion on this issue:
https://github.com/MarvinTeichmann/MultiNet/issues/24
