### ISSUE TITLE
Tensorboard Graph

### ISSUE THREAD

**Issue by DrewNF** [Russell91/TensorBox#38]
Hi Russel!
I'd like to visualize the graph of the model on tensorboard graph panel.
But when I try it gives me back that is not yet defined the graph to be visualized.
I think that from the pb file you load i the file load_googlenetpb the model of inception v3 and from that after you add the layers to get the overfeat model.
I've two question, why you use a pb file instead of the inception model file given by Google?
If what i said before it's right, i can start to modify the code to see the graph model from load_googlenetpb and than from the trin_util and train file for the last layers of the model? 
Bests

**Comment by Russell91** [comment]
Last time I checked, Google's model was inceptionv3 (slow) and not the original GoogLeNet. If this has changed, I'd be happy to switch over. The graph not displaying is a problem that would be nice to fix. I've actually implemented a separate version using VGG through http://github.com/ethereon/caffe-tensorflow, but didn't judge the switch to VGG to be worth the change for users.

**Comment by DrewNF** [comment]
Perfect! I will keep you up to date and try to work on this! bests!

**Comment by DrewNF** [comment]
I add the graph to TensorBoard and make the pull request: https://github.com/Russell91/TensorBox/pull/44

**Comment by DrewNF** [comment]
Added in a separate pull request : #46
