### ISSUE TITLE
Issues with evaluate.ipynb

### ISSUE THREAD

**Issue by mtmarsh2** [Russell91/TensorBox#4]
Hi! I tried running make in utils, since "stitch_wrapper" in needed in the evaluate.ipynb file, but I get a "./hungarian/hungarian.cpp: No such file or directory" error, due to there being no hungarian.cpp file in the utils folder. Is this file somewhere else?

**Comment by Russell91** [comment]
Oops, I thought those filese were unnecessary and deleted it. It should be added back in https://github.com/Russell91/TensorBox/pull/5.
