### ISSUE TITLE
New format for IDL files

### ISSUE THREAD

**Issue by Russell91** [Russell91/TensorBox#52]
Hey guys, I'm thinking about swapping out the IDL files for some sort of json format. Does anyone have any feedback? The existing IDL evaluation toolkit would be kept and extended to work with these alternative files.

**Comment by benslaney** [comment]
Probably using the same format as this: http://image-net.org/download-bboxes would be the way to go for conforming to what seems like it's going to set the standard.

I have already written a nice OS X GUI in Swift for very user friendly modification / creation of the existing format for creating data sets. I can open source it if you think it'll be of any use.

**Comment by Russell91** [comment]
I know about the PASCAL standard. It's really quite horrible to deal with, requiring huge numbers of files and folders. The XML is just terrible as well. It would only be "out of the frying pan and into the fire". This change is more for programmers that want to do some object detection than for CV researchers. I'm aware that this will come at the cost of less portability, but there is just no way I'm going to force XML on anyone.

**Comment by DrewNF** [comment]
For the output or the input? because in the input there's also the xml supported.

**Comment by Russell91** [comment]
@DrewNF Fair enough, you got me there. But the xml is not _encouraged_ in the official readme. I mean, wouldn't everyone prefer just a json format to what we have now, so that you never have to deal with the AnnotationLib craziness unless you just want to use the precision-recall plotter?

**Comment by Russell91** [comment]
Okay, I've added the new format. See http://russellsstewart.com/s/tensorbox/test_boxes.json, for example. TODOs would be to update the make_idl to be a make_json instead.
