### ISSUE TITLE
Change the make_idl.py firle to make_json.py

### ISSUE THREAD

**Issue by Russell91** [Russell91/TensorBox#54]
@Graydyn @DrewNF If anyone involved in the make_idl.py file wants to update it to the new (simpler) format, that would be a nice modification.

**Comment by DrewNF** [comment]
I will do this in the next days, but I'd like to have a full example not only with rects and image path but also label, bb trackid, confidence, frame number, so i can implement a new scripts that covers everything and we don't have to update it again again and again :D

**Comment by Russell91** [comment]
Sounds cool. If you wanted to, you could even make some sort of web-based annotation version. I think that sort of thing is much more useful for mechanical turk. No problem if this isn't your expertise.

**Comment by meetdave06** [comment]
I have modified the script to generate json files.

**Comment by Russell91** [comment]
Thanks @meetdave06
