### ISSUE TITLE
stick_wrapper not yet compiled

### ISSUE THREAD

**Issue by abhijayghildyal** [Russell91/TensorBox#58]
This is what is there inside my stick_wrapper.py file 

    print('ERROR: stitck_wrapper not yet compiled. Please run `cd /path/to/tensorbox/utils && make`')

When i run `make` this is what comes up:

    pip install runcython
    Requirement already satisfied (use --upgrade to upgrade): runcython in /usr/local/lib/python2.7/dist-packages
    Requirement already satisfied (use --upgrade to upgrade): Cython>=0.10 in /usr/local/lib/python2.7/dist-packages (from runcython)
    makecython++ stitch_wrapper.pyx "" "stitch_rects.cpp ./hungarian/hungarian.cpp"

**Comment by Russell91** [comment]
Can you describe the problem?

**Comment by abhijayghildyal** [comment]
This is related to issue https://github.com/Russell91/TensorBox/issues/56
