### ISSUE TITLE
make_json replacement for make_idl

### ISSUE THREAD

**Issue by Alan01252** [Russell91/TensorBox#62]
Hi,

I was wondering if there was a make_json replacement for make_idl. Or whether you've written some converter already from idl -> json.

I know it wouldn't be too hard to make a converter myself, but thought if there's already one out there and tested I should ask :) ( The best programmers are lazy programmers right? ;) ;) )

Thanks

Alan

p.s please don't be hesitate from telling me I'm lazy and to go write it myself ;)

**Comment by Russell91** [comment]
Yeah, I don't think anyone has written this yet. I'll try and get to these various improvements in one more week after the AAAI deadline.

**Comment by Alan01252** [comment]
#54 Same issue as this closing
