### ISSUE TITLE
Issues downloading brainwash.tar.gz

### ISSUE THREAD

**Issue by benjanisa** [Russell91/TensorBox#70]
I am having issues running download_data.sh.

wget http://russellsstewart.com/s/tensorbox/brainwash.tar.gz
repeatedly downloads a ~1GB file (rather than 3.8 GB), is there a known issue here? Or somewhere else I can download the dataset from?

**Comment by botasb** [comment]
Hi benjasina. 
Are you behind any kind of proxy? (maybe you are at work) There could be some limitations .... I had the same issue until I downloaded from my home connection.

**Comment by benjanisa** [comment]
Thanks @botasb. I've tried at home and at work (and at a friend's home), none of which worked. 

Not sure what else it could be?

**Comment by benslaney** [comment]
it uses curl right? (or wget, cant remember which), cant you just run the command again manually with the resume option? that’s what i had to do when i was using a lousy connection to get it

**Comment by benjanisa** [comment]
That worked! (it uses wget). Thank you

**Comment by DiegoGLagash** [comment]
Same issue here, the connection broke after 1.3G. And the server does not resume, curl says "curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume."
