### ISSUE TITLE
Adding Tensorbox in Caltech Evaluation Code

### ISSUE THREAD

**Issue by vivekarvind** [Russell91/TensorBox#84]
Is it possible to add the results of TensorBox in the Caltech Evaluation Code? There is a modified version of the TUD_Brussels dataset [here](https://www.vision.caltech.edu/Image_Datasets/CaltechPedestrians/datasets/TudBrussels/). Can the detection results of TensorBox be put into use? Any help appreciated. Thanks.

**Comment by Russell91** [comment]
Yes, it can be used there. Is there something specifically we can help with?

**Comment by vivekarvind** [comment]
Sorry my bad. I was able to solve it myself. Thank you! Although, I have another question. Are the graphs mentioned in the paper and the evaluate.ipynb equivalent to ROC graphs? I understand that the graphs are generated between 1-precision in the x-axis and recall (sensitivity) in the y-axis. If not, how do I generate the ROC curve while evaluating? Please help.

Thanks.
