### ISSUE TITLE
Training on Multiple GPUs

### ISSUE THREAD

**Issue by piyushshri** [Russell91/TensorBox#87]
The argument --gpu sets CUDA_VISIBLE_DEVICES to an appropriate GPU and uses it for training. However, if a machine has multiple GPUs, only one of them can be used at a time.
For example, if --gpu is set to 0, the first GPU will get used, if it is set to 1, the second will get used and so on. No two GPUs are being utilized at a time.

**Comment by mishra011** [comment]
Hey, @piyushshri Can you tell how much did it take to train it on GPU.
