### ISSUE TITLE
make hungarian fails with error

### ISSUE THREAD

**Issue by virajago** [Russell91/TensorBox#90]
make hungarian fails with error

Undefined symbols for architecture x86_64:
  "tensorflow::DEVICE_CPU", referenced from:
.........
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [hungarian/hungarian.so] Error 1

running on 
OSX 10.12
NVIDIA GeForce GT 750M 2048 MB
Tensorflow 0.11.0rc0
CUDA 8

**Comment by virajago** [comment]
@Russell91 - any pointers would be appreciated. Btw am using Tensorflow with GPU support. Hope tensorbox works with GPU?

**Comment by jbrozena22** [comment]
Same issue here. Any suggestions?

**Comment by jbrozena22** [comment]
I solved it. Per the note here: https://www.tensorflow.org/versions/r0.11/how_tos/adding_an_op/index.html

> On Mac OS X, the additional flag "-undefined dynamic_lookup" is required when building the .so file.

So I added -undefined dynamic_lookup to the Makefile:
```
hungarian/hungarian.so:
	cd hungarian && \
	TF_INC=$$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())') && \
	g++ -std=c++11 -shared hungarian.cc -o hungarian.so -fPIC -I $$TF_INC -undefined dynamic_lookup

```

Then ran make hungarian and it all worked.

**Comment by virajago** [comment]
@jbrozena22 Thanks for the note. Adding the flag solved the issue for me

**Comment by Russell91** [comment]
If someone can submit a pull request adding a Makefile check for DARWIN,
that could help others with the same issue.
