### ISSUE TITLE
Using trained model on new images

### ISSUE THREAD

**Issue by Blair-Young** [Russell91/TensorBox#91]
Hey, I was wondering how to use the model once it's been trained. I know you mentioned you run your own images through the evaluation.ipynb file but I'm not entirely sure how. Will the input also have to be the same dimensions as the training data?

**Comment by vinothg** [comment]
In evaluate.ipynb, load your hypes_file, train_idl, pred_idl and restore your saved model.

In the for loop, load your images and it should work.

**Comment by Blair-Young** [comment]
Thanks, have you had any experience with testing your own unseen images while still using the brainwash train_idl ?
