### ISSUE TITLE
num_gt_.clear() outside batch loop?

### ISSUE THREAD

**Issue by temporaer** [Russell91/TensorBox#92]
This list 

https://github.com/Russell91/TensorBox/blob/master/utils/hungarian/hungarian.cc#L624

- gets reset only once per batch, 
- is sequentially modified while processing batch elements
- is part of the assignment calculation inside a single batch element

Normally, batch samples should be processed independently of each other?

As far as I understand, this should be the total number of ground truth boxes for a single class in _one_ batch element.

**Comment by Russell91** [comment]
Yea, good question. This is a vector of length batch_size storing the number of gt in each image of the batch.
