### ISSUE TITLE
Number of input mismatch for hungarian op - python3 - tensorflow0.10

### ISSUE THREAD

**Issue by dawood95** [Russell91/TensorBox#95]
Traceback (most recent call last):
  File "train.py", line 533, in <module>
    main()
  File "train.py", line 530, in main
    train(H, test_images=[])
  File "train.py", line 443, in train
    smooth_op, global_step, learning_rate, encoder_net) = build(H, q)
  File "train.py", line 352, in build
    grads, norm = tf.clip_by_global_norm(tf.gradients(loss['train'], tvars), H['clip_norm'])
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gradients.py", line 486, in gradients
    _VerifyGeneratedGradients(in_grads, op)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gradients.py", line 255, in _VerifyGeneratedGradients
    "inputs %d" % (len(grads), op.node_def, len(op.inputs)))
ValueError: Num gradients 1 generated for op name: "decoder_1/Hungarian"
op: "Hungarian"
input: "decoder/concat"
input: "decoder_1/Reshape"
input: "decoder_1/Cast"
input: "decoder_1/Hungarian/overlap_threshold"
 do not match num inputs 4

Looks like a mismatch of some type. Not sure how to fix this

**Comment by Russell91** [comment]
Tensorflow version?

**Comment by dawood95** [comment]
tried both 0.11 and 0.10. Same error

**Comment by Russell91** [comment]
Very strange. I'm not getting this error. Have you changed anything else
about the repository? And are you confident that you compiled hungarian.so
correctly?

The backprop is implement in python and maps a 0 gradient over the inputs.
So there should be the correct number of gradients.

**Comment by dawood95** [comment]
I changed a couple of things to port it to python3, but all basic things (adding paranthesis to print statements, converting iteritems to items). I will try running it without the changes and let you know!

**Comment by dawood95** [comment]
It was a porting problem. Not sure what the problem exactly is. I am just going to use python2 for now. Thanks!
