### ISSUE TITLE
no results shown in the evaluation ipython notebook

### ISSUE THREAD

**Issue by lazydroid** [Russell91/TensorBox#99]
I have opened the notebook, and seen nice pictures with green rectangles and red graph going into 0.9x are in the bottom. Then I have decided to run the notebook, clicked "run" on every block of the code, and now the pictures are just pictures, without any detected faces, and the graph at the bottom shows nothing.

Am I correct to think that there's a pretrained model downloaded by "download" script and this pretrained model is used in the eval. notebook, or do I have to train my own model to be able to see any results?

ps. notebook ran without any errors, tensorflow (0.11.0rc0).

**Comment by Russell91** [comment]
Let me look into this. We recently upgraded to tfslim and changed the
notebook code.

**Comment by lazydroid** [comment]
i'm training the default dataset, now it's iteration 134k and there are no red boxes on X_pred.jpg pictures in the output/overfeat_rezom_$datetime folder, though I expected they should show up by this time, at least on some pictures. there were a few occasional red boxed on X_pred.jpg files around iteration 30k, but looked like a random noise. now there are none at all.

**Comment by Russell91** [comment]
Yeah, you should be getting boxes by about 5k iterations. But you should not need to train your own network to get outputs. How many frames per second did the notebook report?

**Comment by jastarex** [comment]
Similar issue here. There are no detected bboxes on the notebook using the pretrained `save.ckpt-150000v2` model, though occasionally a horizontal green line appears in some images (which seems a bbox with `H=0, W=img_width`).

**Comment by Russell91** [comment]
Okay @jastarex @lazydroid sorry guys. Made a big commit last night and then added a small change that messed things up at the end. The reversion is here: https://github.com/Russell91/TensorBox/commit/107f0ad667ba703523a2dfa307c80d1ac954c146

If you `git pull origin master`, and restart your ipython notebook, you should be able to run the pretrained model.

**Comment by jastarex** [comment]
@Russell91 Many thanks for your update, Russell, issue solved.

**Comment by lazydroid** [comment]
@Russell91 works great, thanks a lot !
